# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.custom", "");
user_pref("browser.download.importedFromSqlite", true);
user_pref("consoleservice.enabled", true);
user_pref("device.storage.writable.name", "sdcard");
user_pref("devtools.eventlooplag.threshold", 100);
user_pref("dom.mms.requestStatusReport", false);
user_pref("dom.mozApps.homescreenURL", "Sentinel Value");
user_pref("dom.mozApps.use_reviewer_certs", false);
user_pref("dom.sms.maxReadAheadEntries", 7);
user_pref("dom.sms.requestStatusReport", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.lastAppVersion", "37.0");
user_pref("extensions.lastPlatformVersion", "37.0");
user_pref("extensions.shownSelectionUI", true);
user_pref("font.internaluseonly.changed", false);
user_pref("gecko.buildID", "20150330002503");
user_pref("gecko.mstone", "37.0");
user_pref("intl.accept_languages", "en-US, en");
user_pref("layers.composer2d.enabled", false);
user_pref("layers.effect.contrast", "0.0");
user_pref("layers.effect.grayscale", false);
user_pref("layers.effect.invert", false);
user_pref("marionette.contentListener", false);
user_pref("privacy.donottrackheader.value", 1);
user_pref("ril.debugging.enabled", false);
user_pref("ril.radio.disabled", false);
user_pref("security.turn_off_all_security_so_that_viruses_can_take_over_this_computer", true);
user_pref("toolkit.telemetry.previousBuildID", "20150330002503");
